apiVersion: v1
kind: LimitRange
metadata:
  name: prodlimits
  namespace: projekt11
spec:
  limits:
  - type: Pod 
    max:
      cpu: "2" 
      memory: 1Gi 
      ephemeral-storage: 500Mi
  - type: Container
    min:
      cpu: 100m
      memory: 3Mi 
    maxLimitRequestRatio:
      cpu: "10"
      memory: "3"

